#!/bin/bash
echo "Hello World"
plink pi@192.168.4.1 -pw qwerasdf < barcode_scanner_image.py "cat > ~/barcode_scanner_image.py"
plink pi@192.168.4.1 -pw qwerasdf < motortesting.py "cat > ~/motortesting.py"
plink pi@192.168.4.1 -pw qwerasdf < pathfind.py "cat > ~/pathfind.py"
plink pi@192.168.4.1 -pw qwerasdf < imageTesting.py "cat > ~/imageTesting.py"
#plink pi@192.168.4.1 -pw qwerasdf < pyzbar-0.1.8-py2.py3-none-any.whl "cat > ~/pyzbar-0.1.8-py2.py3-none-any.whl"
plink pi@192.168.4.1 -pw qwerasdf #< micromelon_server.py
#plink pi@192.168.4.1 -pw qwerasdf < "python3 micromelon_server.py"


